export interface clienteVelho{
    id : number,
    id_sirius : number,
    status : string,
    dataFoiCadastrado : Date,
    dataUltimaAtualizacao : Date,
    razaoSocial : string,
    fantasia : string | null,
    cpf : string,
    cnpj : string,
    idEstrangeiro : string | null,
    indIE : string | null,
    inscEstadual : string | null,
    inscMunicipal : string | null,
    tipoCliente : string,
    exclusivo : number | null,
    vendedor_id : number | null,
    vendedor_id_sirius : number | null,
    vendedor_nome : string | null,
    lista_preco_id : number | null,
    lista_preco_nome : string | null,
    condicao_pagamento_id : number | null,
    contato : string | null,
    contato_nome : string | null,
    condicao_pagamento_id_sirius : number | null
}

export interface clienteNovo {
    id_cliente : number,
    id_sirius_cliente : number | null,
    status_cliente : string,
    created_at_cliente : Date,
    updated_at_cliente : Date,
    razao_social_cliente : string,
    fantasia_cliente : string | null,
    cpf_cliente : string,
    cnpj_cliente : string,
    id_estrangeiro_cliente : string,
    ind_ie_cliente : string,
    insc_estadual_cliente : string,
    insc_municipal_cliente : string,
    tipo_cliente : string,
    exclusivo_cliente : number,
    id_vendedor_cliente : number,
    id_vendedor_sirius_cliente : number,
    id_lista_preco_cliente : number,
    id_condicao_pagamento_cliente : number,
    contato_cliente : string,
    nm_contato_cliente : string,
    id_condicao_pagamento_sirius_cliente :number
}